root: true
env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent: [2, 2]
  linebreak-style: [2, unix]
  no-alert: 0
  no-console: 0
  quotes: [2, single]
  react/jsx-no-undef: 2
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  semi: [2, always]
  sort-imports: [2, {ignoreCase: true, ignoreMemberSort: true, memberSyntaxSortOrder: [all, single, multiple, none]}]
globals:
  process: true
  module: true
