root: true
env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  # TODO alert and console should be failures later on with explicit disabling if needed
  no-alert: 0
  no-console: 0
  no-case-declarationn: 0
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/jsx-space-before-closing: [2, never]
  indent: [2, 2]
  linebreak-style: [2, unix]
  quotes: [2, single]
  semi: [2, always]
globals:
  moment: true
