
//
// node actions
//

export const NODE_LIST_REQUEST = "NODE_LIST_REQUEST";
export const NODE_LIST_SUCCESS = "NODE_LIST_SUCCESS";
export const NODE_LIST_FAILURE = "NODE_LIST_FAILURE";

export const NODE_CREATE_REQUEST = "NODE_CREATE_REQUEST";
export const NODE_CREATE_SUCCESS = "NODE_CREATE_SUCCESS";
export const NODE_CREATE_FAILURE = "NODE_CREATE_FAILURE";

export const NODE_UPDATE_REQUEST = "NODE_UPDATE_REQUEST";
export const NODE_UPDATE_SUCCESS = "NODE_UPDATE_SUCCESS";
export const NODE_UPDATE_FAILURE = "NODE_UPDATE_FAILURE";

export const NODE_DELETE_REQUEST = "NODE_DELETE_REQUEST";
export const NODE_DELETE_SUCCESS = "NODE_DELETE_SUCCESS";
export const NODE_DELETE_FAILURE = "NODE_DELETE_FAILURE";

//
// user actions
//

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILURE = "USER_CREATE_FAILURE";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

export const USER_TOKEN_REQUEST = "USER_TOKEN_REQUEST";
export const USER_TOKEN_SUCCESS = "USER_TOKEN_SUCCESS";
export const USER_TOKEN_FAILURE = "USER_TOKEN_FAILURE";

//
// user feed actions
//

export const FEED_REQUEST = "FEED_REQUEST";
export const FEED_SUCCESS = "FEED_SUCCESS";
export const FEED_FAILURE = "FEED_FAILURE";

//
// repo actions
//

export const REPO_REQUEST = "REPO_REQUEST";
export const REPO_SUCCESS = "REPO_SUCCESS";
export const REPO_FAILURE = "REPO_FAILURE";

export const REPO_PATCH_REQUEST = "REPO_PATCH_REQUEST";
export const REPO_PATCH_SUCCESS = "REPO_PATCH_SUCCESS";
export const REPO_PATCH_FAILURE = "REPO_PATCH_FAILURE";

export const REPO_LIST_REQUEST = "REPO_LIST_REQUEST";
export const REPO_LIST_SUCCESS = "REPO_LIST_SUCCESS";
export const REPO_LIST_FAILURE = "REPO_LIST_FAILURE";

//
// repo encryption
//

export const ENCRYPT_REQUEST = "ENCRYPT_REQUEST";
export const ENCRYPT_SUCCESS = "ENCRYPT_SUCCESS";
export const ENCRYPT_FAILURE = "ENCRYPT_FAILURE";

//
// build actions
//

export const BUILD_LIST_REQUEST = "BUILD_LIST_REQUEST";
export const BUILD_LIST_SUCCESS = "BUILD_LIST_SUCCESS";
export const BUILD_LIST_FAILURE = "BUILD_LIST_FAILURE";

export const BUILD_REQUEST = "BUILD_REQUEST";
export const BUILD_SUCCESS = "BUILD_SUCCESS";
export const BUILD_FAILURE = "BUILD_FAILURE";

export const BUILD_RESTART_REQUEST = "BUILD_RESTART_REQUEST";
export const BUILD_RESTART_SUCCESS = "BUILD_RESTART_SUCCESS";
export const BUILD_RESTART_FAILURE = "BUILD_RESTART_FAILURE";

//
// job actions
//

export const JOB_CANCEL_REQUEST = "JOB_CANCEL_REQUEST";
export const JOB_CANCEL_SUCCESS = "JOB_CANCEL_SUCCESS";
export const JOB_CANCEL_FAILURE = "JOB_CANCEL_FAILURE";

//
// log actions
//

export const LOG_REQUEST = "LOG_REQUEST";
export const LOG_SUCCESS = "LOG_SUCCESS";
export const LOG_FAILURE = "LOG_FAILURE";
