
export const CRON_LIST = 'CRON_LIST';
export const CRON_LIST_LOADING = 'CRON_LIST_LOADING';
export const CRON_LIST_SUCCESS = 'CRON_LIST_SUCCESS';
export const CRON_LIST_FAILURE = 'CRON_LIST_FAILURE';

export const CRON_DELETE = 'CRON_DELETE';
export const CRON_DELETE_LOADING = 'CRON_DELETE_LOADING';
export const CRON_DELETE_SUCCESS = 'CRON_DELETE_SUCCESS';
export const CRON_DELETE_FAILURE = 'CRON_DELETE_FAILURE';

export const CRON_CREATE = 'CRON_CREATE';
export const CRON_CREATE_LOADING = 'CRON_CREATE_LOADING';
export const CRON_CREATE_SUCCESS = 'CRON_CREATE_SUCCESS';
export const CRON_CREATE_FAILURE = 'CRON_CREATE_FAILURE';
